name: "Big Query Comment Table"
description: "Create a table comment from BigQuery"
inputs:
  project-id:
    description: "The project ID in GCP"
    required: true
  query:
    description: "Query to execute"
    required: true
outputs:
  table:
    description: "The response in markdown table"
runs:
  using: "node20"
  main: "dist/index.js"
